import { ValidBookName } from "kingjames";

type BookOption = { key: number; value: ValidBookName };
const bookOptions: BookOption[] = [
  { key: 1, value: "genesis" },
  { key: 2, value: "exodus" },
  { key: 3, value: "leviticus" },
  { key: 4, value: "numbers" },
  { key: 5, value: "deuteronomy" },
  { key: 6, value: "joshua" },
  { key: 7, value: "judges" },
  { key: 8, value: "ruth" },
  { key: 9, value: "1 samuel" },
  { key: 10, value: "2 samuel" },
  { key: 11, value: "1 kings" },
  { key: 12, value: "2 kings" },
  { key: 13, value: "1 chronicles" },
  { key: 14, value: "2 chronicles" },
  { key: 15, value: "ezra" },
  { key: 16, value: "nehemiah" },
  { key: 17, value: "esther" },
  { key: 18, value: "job" },
  { key: 19, value: "psalms" },
  { key: 20, value: "proverbs" },
  { key: 21, value: "ecclesiastes" },
  { key: 22, value: "song of solomon" },
  { key: 23, value: "isaiah" },
  { key: 24, value: "jeremiah" },
  { key: 25, value: "lamentations" },
  { key: 26, value: "ezekiel" },
  { key: 27, value: "daniel" },
  { key: 28, value: "hosea" },
  { key: 29, value: "joel" },
  { key: 30, value: "amos" },
  { key: 31, value: "obadiah" },
  { key: 32, value: "jonah" },
  { key: 33, value: "micah" },
  { key: 34, value: "nahum" },
  { key: 35, value: "habakkuk" },
  { key: 36, value: "zephaniah" },
  { key: 37, value: "haggai" },
  { key: 38, value: "zechariah" },
  { key: 39, value: "malachi" },
  { key: 40, value: "matthew" },
  { key: 41, value: "mark" },
  { key: 42, value: "luke" },
  { key: 43, value: "john" },
  { key: 44, value: "acts" },
  { key: 45, value: "romans" },
  { key: 46, value: "1 corinthians" },
  { key: 47, value: "2 corinthians" },
  { key: 48, value: "galatians" },
  { key: 49, value: "ephesians" },
  { key: 50, value: "philippians" },
  { key: 51, value: "colossians" },
  { key: 52, value: "1 thessalonians" },
  { key: 53, value: "2 thessalonians" },
  { key: 54, value: "1 timothy" },
  { key: 55, value: "2 timothy" },
  { key: 56, value: "titus" },
  { key: 57, value: "philemon" },
  { key: 58, value: "hebrews" },
  { key: 59, value: "james" },
  { key: 60, value: "1 peter" },
  { key: 61, value: "2 peter" },
  { key: 62, value: "1 john" },
  { key: 63, value: "2 john" },
  { key: 64, value: "3 john" },
  { key: 65, value: "jude" },
  { key: 66, value: "revelation" },
];

export { type BookOption, bookOptions };
